---

- name: 'Reload service "{{ service_name }}"'
  listen: service reload
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    daemon_reload: true
    state: reloaded

- name: 'Enable service "{{ service_name }}"'
  listen: service restart
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    daemon_reload: true
    enabled: true

- name: 'Restart service "{{ service_name }}"'
  listen: service restart
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    daemon_reload: true
    state: restarted
