---

- name: 'Reload service "{{ service_name }}"'
  listen: service reload
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    state: reloaded

- name: 'Restart service "{{ service_name }}"'
  listen: service restart
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    state: restarted
