# Create kernel symlinks

- name: Find initrd
  ansible.builtin.find:
    paths: /boot
    patterns: initrd.img-*
  register: initrd

- name: Create initrd.img link
  ansible.builtin.file:
    src: '{{ (initrd.files | sort(attribute="path"))[-1]["path"] | basename }}'
    dest: /boot/initrd.img
    state: link
    force: true

- name: Find vmlinuz
  ansible.builtin.find:
    paths: /boot
    patterns: vmlinuz-*
  register: vmlinuz

- name: Create vmlinuz link
  ansible.builtin.file:
    src: '{{ (vmlinuz.files | sort(attribute="path"))[-1]["path"] | basename }}'
    dest: /boot/vmlinuz
    state: link
    force: true

# Create grub config

- name: Create config
  ansible.builtin.copy:
    src: grub.cfg
    dest: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: u=rw,go=r
