# Install package

- name: Package
  ansible.builtin.apt:
    name:
      - libicu72
      - libssl3
      - jq
    state: present

# Create lib

- name: Create lib directory
  ansible.builtin.file:
    path: '{{ jackett_lib }}'
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Check lib
  ansible.builtin.shell: >
    set -e -o pipefail;
    n=$(wget -q -O - "{{ jackett_archive }}" |
        tar -tzf - |
        grep -F -e "Jackett/jackett_launcher.sh" |
        wc -l
       );
    [ "$n" == 1 ]
  args:
    executable: /bin/bash
    creates: '{{ joal_lib }}/jackett_launcher.sh'
  check_mode: false
  changed_when: false
  register: check_lib
  tags:
    - skip_ansible_lint

- name: Create lib
  ansible.builtin.unarchive:
    src: '{{ jackett_archive }}'
    remote_src: true
    dest: '{{ jackett_lib }}'
    owner: root
    group: root
    mode: u+rw,go-w+r
    creates: '{{ jackett_lib }}/jackett_launcher.sh'
    extra_opts:
      - --transform
      - s/^Jackett//
  when: not ansible_check_mode
  register: create_lib

# Create var

- name: Create var directory
  ansible.builtin.file:
    path: '{{ jackett_var }}'
    state: directory
    owner: '{{ jackett_user }}'
    group: '{{ jackett_user }}'
    mode: ug=rwx,o=rx

- name: Check config
  ansible.builtin.stat:
    path: '{{ jackett_var }}/ServerConfig.json'
  register: check_config

- name: Init config
  ansible.builtin.copy:
    content: '{}'
    dest: '{{ jackett_var }}/ServerConfig.json'
    owner: '{{ jackett_user }}'
    group: '{{ jackett_user }}'
    mode: u=rw,go=r
  when: not check_config.stat.exists

- name: Create ansible config
  ansible.builtin.copy:
    content: '{{ jackett_config | to_json }}'
    dest: '{{ jackett_var }}/ServerConfig.json.ansible'
    owner: '{{ jackett_user }}'
    group: '{{ jackett_user }}'
    mode: u=rw,go=r
  register: create_config

- name: Update config
  ansible.builtin.shell: >
    set -e -o pipefail
    cat {{ jackett_var }}/ServerConfig.json {{ jackett_var }}/ServerConfig.json.ansible | jq -s add > {{ jackett_var }}/ServerConfig.json.tmp;
    cat {{ jackett_var }}/ServerConfig.json.tmp > {{ jackett_var }}/ServerConfig.json;
    rm {{ jackett_var }}/ServerConfig.json.tmp
  when: create_config is changed
  changed_when: true

- name: Fix permissions
  ansible.builtin.shell: >
    set -e -o pipefail;
    find {{ jackett_var }} \
      ! -user root \
      ! -user {{ jackett_user }} \
      -print \
      -exec chown {{ jackett_user }}. {} \; \
      | wc -l
  args:
    executable: /bin/bash
  register: fix_permissions
  changed_when: fix_permissions.stdout != '0'
  tags: fix_permissions

# Create service

- name: Create service
  ansible.builtin.template:
    src: service.j2
    dest: '/etc/systemd/system/{{ jackett_name }}.service'
    owner: root
    group: root
    mode: u=rw,go=r
  register: create_service

- name: Enable
  ansible.builtin.systemd:
    name: '{{ jackett_name }}'
    enabled: true

- name: Restart
  ansible.builtin.systemd:
    name: '{{ jackett_name }}'
    daemon_reload: true
    state: restarted
  when: >
    create_lib is changed or
    create_config is changed or
    create_service is changed

- name: Start
  ansible.builtin.systemd:
    name: '{{ jackett_name }}'
    state: started
