---

- name: Include "archive" role
  ansible.builtin.include_role:
    name: archive
  vars:
    archive_url:
      "https://github.com/FlareSolverr/FlareSolverr/releases/download/\
       v{{ solverr_version }}/flaresolverr_linux_x64.tar.gz"
    archive_dest: '{{ service_opt }}/bin-{{ solverr_version }}.tar.gz'
    archive_content: '{{ __solverr_bin }}'
    archive_creates: '{{ __solverr_bin }}/flaresolverr'
    archive_transform: '\.\/flaresolverr'
