---

- name: 'Logical volume "{{ __lvm_lv_volume }}" exists'
  community.general.lvol:
    vg: '{{ lvm_vg_name }}'
    lv: '{{ lvm_lv_name }}'
    size: '{{ lvm_lv_size }}'
    opts: '{{ lvm_lv_opts }}'
    resizefs: true

- name: 'Logical volume "{{ __lvm_lv_volume }}" is formatted'
  community.general.filesystem:
    dev: '/dev/{{ __lvm_lv_volume }}'
    fstype: ext4
    force: false
    opts: -m 0

- name: 'Service "{{ __lvm_lv_service }}" exists'
  ansible.builtin.template:
    src: mount.j2
    dest: '/etc/systemd/system/{{ __lvm_lv_service }}'
    owner: root
    group: root
    mode: u=rw,go=r

- name: 'Service "{{ __lvm_lv_service }}" is enabled'
  ansible.builtin.systemd:
    name: '{{ __lvm_lv_service }}'
    enabled: true

- name: 'Service "{{ __lvm_lv_service }}" is started'
  ansible.builtin.systemd:
    name: '{{ __lvm_lv_service }}'
    daemon_reload: true
    state: started
