# Create VG

- name: Create
  community.general.lvol:
    vg: '{{ vg_name }}'
    lv: '{{ lv_name }}'
    size: '{{ lv_size }}'
    opts: '{{ lv_opts }}'
    resizefs: true
  register: create

- name: Format
  community.general.filesystem:
    dev: '/dev/{{ vg_name }}/{{ lv_name }}'
    fstype: ext4
    force: false

- name: Reserved
  ansible.builtin.command: >
    /usr/sbin/tune2fs -m 0 /dev/{{ vg_name }}/{{ lv_name }}
  changed_when: true
  check_mode: false
  when: create.changed

- name: Mount
  ansible.posix.mount:
    src: '/dev/mapper/{{ vg_name }}-{{ lv_name }}'
    path: '{{ lv_mount }}'
    fstype: ext4
    opts: rw,relatime,nofail
    state: mounted
