repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint -v --force-color
        language: system
        pass_filenames: false
        always_run: true
      - id: versions
        name: versions
        entry: nix-shell --command "print_versions > versions"
        language: system
        pass_filenames: false
        always_run: true
