repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint -v --force-color
        language: system
        pass_filenames: false
        always_run: true
