---

repos:
  - repo: local
    hooks:
      - id: ansiblelint
        name: ansiblelint
        language: system
        entry: ansible-lint -v --force-color
        files: "^(host_vars|inventory|roles|templates|(server|virtual)\\.yml)"
        pass_filenames: true
        always_run: false
        stages: [commit]
        types: [file]
      - id: nixfmt
        name: nixfmt
        language: system
        entry: nixfmt
        files: "\\.nix$"
        pass_filenames: true
        always_run: false
        stages: [commit]
        types: [file]
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/mrtazz/checkmake
    rev: 0.2.2
    hooks:
      - id: checkmake
        name: checkmake
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: yamllint
        files:
          "^(\\.pre-commit-config.yaml|\\.ansible-lint)$|\\.github/.*\\.yml$"
