repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.17.2
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible-core==2.15.3
          - passlib==1.7.4
