# Bootstrap playbook
# Run during debian install, before first boot

- name: Bootstrap
  hosts: server
  gather_facts: no
  become: true
  tags: bootstrap # <- debian installer tag
  roles:
  - role: bootstrap/systemctl
  - role: bootstrap/cdrom
  - role: bootstrap/grub
  - role: bootstrap/keyboard
  - role: bootstrap/playbook

# All playbooks below run automatically during first boot

- name: Base
  hosts: server
  gather_facts: no
  become: true
  roles:
  - role: network
  - role: apt
  - role: ssh-server
    tags: ssh-server
    ssh_server_key: server/ssh/server
    ssh_server_key_pub: server/ssh/server.pub
  - role: user
    tags: user
    user_name: root
    user_password: '{{ password.root }}'
    user_shell: /bin/zsh
  - role: user
    tags: user
    user_password: '{{ password.user }}'
    user_key_pub: server/ssh/user.pub
    user_shell: /bin/zsh
    user_sudo: true
  - role: user
    tags: user
    user_name: ansible
    user_password: '{{ password.ansible }}'
    user_key_pub: server/ssh/ansible.pub
    user_shell: /bin/zsh
    user_sudo: yes-no-password
  - role: ohmyzsh
    ohmyzsh_user_name: root
  - role: ohmyzsh
    ohmyzsh_user_name: '{{ user_name }}'
  - role: ohmyzsh
    ohmyzsh_user_name: ansible

- name: Data Disks
  hosts: server
  gather_facts: false
  become: true
  tags: data
  roles:
  - role: lvm/vg
    vg_name: data
    vg_pvs:
    - /dev/disk/by-id/ata-ST10000NT001-3LY101_WWY07EXB
    - /dev/disk/by-id/ata-ST10000NT001-3LY101_WP0023PL

- name: Media Softwares
  hosts: server
  gather_facts: false
  become: true
  tags: media
  roles:
  - role: lvm/lv
    tags: data
    vg_name: data
    lv_name: media
    lv_size: 3T
    lv_opts: --type raid1 --nosync
  - role: user-service
    tags: data
    user_service_name: media
  - role: user-service
    tags: data
    user_service_name: media
  - role: library
    tags: data
    library_user: media
    library_var: /mnt/data/media/library
  - role: plex
    tags: plex
    plex_user: media
    plex_var: /mnt/data/media/plex
  - role: qbittorrent
    tags: qbittorrent
    qbittorrent_var: /mnt/data/media/qbittorrent
    qbittorrent_user: media
    qbittorrent_peer_port: 50000
    qbittorrent_interface: '{{ network_interface }}'
  - role: sabnzbd
    tags: sabnzbd
    sabnzbd_var: /mnt/data/media/sabnzbd
    sabnzbd_user: media

- name: NGINX
  hosts: server
  gather_facts: false
  become: true
  tags: nginx
  roles:
  - role: nginx
    nginx_config: server/nginx.conf.j2
