---

- name: Include "system.yml"
  when: user_system
  ansible.builtin.include_tasks:
    file: system.yml

- name: Include "user.yml"
  when: not user_system
  ansible.builtin.include_tasks:
    file: user.yml
