- name: Create password dir
  ansible.builtin.file:
    path: '{{ config_dir }}/password'
    state: directory

- name: Generate password
  ansible.builtin.shell: >
    echo "{{ item.var }}: $(bw generate -p)" >
    {{ config_dir }}/password/{{ item.var }}.yml
  args:
    creates: '{{ config_dir }}/password/{{ item.var }}.yml'
  no_log: true

- name: Include password
  ansible.builtin.include_vars: '{{ config_dir }}/password/{{ item.var }}.yml'
  no_log: true
