- name: Remove debian sources
  file:
    path: /etc/apt/sources.list
    state: absent

- name: Create directory
  file:
    path: /etc/apt/sources.list.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Create sources
  copy:
    src: debian.list
    dest: /etc/apt/sources.list.d/debian.list
    owner: root
    group: root
    mode: u=rw,go=r
  register: sources

- name: Update cache
  apt:
    update_cache: true
  when: sources is changed

- name: Update old cache
  apt:
    update_cache: true
    cache_valid_time: 3600
