- name: Config
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Create config dir
      ansible.builtin.file:
        path: '{{ config_dir }}'
        state: directory
  roles:
    - role: config_password
      config_password_output: '{{ config_dir }}/raspi_password.yml'
      config_password_vars:
        - name: password_root
        - name: password_regular
        - name: password_github
        - name: password_pihole
    - role: config_hash
      config_hash_output: '{{ config_dir }}/raspi_hash.yml'
      config_hash_vars:
        - hash_name: hash_root
          salt_name: salt_root
          password_name: password_root
          method: crypt
        - hash_name: hash_regular
          salt_name: salt_regular
          password_name: password_regular
          method: crypt
        - hash_name: hash_github
          salt_name: salt_github
          password_name: password_github
          method: crypt
        - hash_name: hash_pihole
          password_name: password_pihole
          method: sha256
    - role: config_password
      config_password_output: '{{ config_dir }}/server_password_1.yml'
      config_password_vars:
        - name: password_root
        - name: password_regular
        - name: password_github
    - role: config_password
      config_password_output: '{{ config_dir }}/server_password_2.yml'
      config_password_vars:
        - name: password_samba
        - name: password_grafana
        - name: password_jackett_key
          method: token
          length: 32
        - name: password_jackett_id
          method: token
          length: 64
    - role: config_hash
      config_hash_output: '{{ config_dir }}/server_hash.yml'
      config_hash_vars:
        - hash_name: hash_root
          salt_name: salt_root
          password_name: password_root
          method: crypt
        - hash_name: hash_regular
          salt_name: salt_regular
          password_name: password_regular
          method: crypt
        - hash_name: hash_github
          salt_name: salt_github
          password_name: password_github
          method: crypt
    - role: config_ssh_keys
      config_ssh_keys:
        - '{{ config_dir }}/raspi_ssh_keys_host'
        - '{{ config_dir }}/raspi_ssh_keys_{{ user_name_regular }}'
        - '{{ config_dir }}/raspi_ssh_keys_{{ user_name_github }}'
        - '{{ config_dir }}/server_ssh_keys_host'
        - '{{ config_dir }}/server_ssh_keys_{{ user_name_regular }}'
        - '{{ config_dir }}/server_ssh_keys_{{ user_name_github }}'
    - role: config_ssh_known_host
      config_ssh_known_host_output: '{{ config_dir }}/ssh_known_host'
      config_ssh_known_host_vars:
        - key_pub: '{{ config_dir }}/raspi_ssh_keys_host.pub'
          hosts:
            - '{{ hostvars.raspi.network_private_address }}'
            - '{{ hostvars.raspi.network_local_domain }}'
            - '{{ network_public_domain }}'
        - key_pub: '{{ config_dir }}/server_ssh_keys_host.pub'
          hosts:
            - '{{ hostvars.server.network_private_address }}'
            - '{{ hostvars.server.network_local_domain }}'
            - '{{ network_public_domain }}'
    - role: config_ssh_client
      config_ssh_client_output: '{{ config_dir }}/ssh_client'
      config_ssh_client_known_host: '{{ config_dir }}/ssh_known_host'
      config_ssh_client_vars:
        - user: '{{ user_name_regular }}'
          port: '{{ hostvars.raspi.port_ssh }}'
          key: '{{ config_dir }}/raspi_ssh_keys_{{ user_name_regular }}'
          hosts:
            - host: '{{ hostvars.raspi.network_private_address }}'
            - host: '{{ hostvars.raspi.network_local_domain }}'
            - host: '{{ hostvars.raspi.network_public_sub_domain }}'
              name: '{{ network_public_domain }}'
        - user: '{{ user_name_github }}'
          port: '{{ hostvars.raspi.port_ssh }}'
          key: '{{ config_dir }}/raspi_ssh_keys_{{ user_name_github }}'
          hosts:
            - host: '{{ hostvars.raspi.network_private_address }}'
            - host: '{{ hostvars.raspi.network_local_domain }}'
            - host: '{{ hostvars.raspi.network_public_sub_domain }}'
              name: '{{ network_public_domain }}'
        - user: '{{ user_name_regular }}'
          port: '{{ hostvars.server.port_ssh }}'
          key: '{{ config_dir }}/server_ssh_keys_{{ user_name_regular }}'
          hosts:
            - host: '{{ hostvars.server.network_private_address }}'
            - host: '{{ hostvars.server.network_local_domain }}'
            - host: '{{ hostvars.server.network_public_sub_domain }}'
              name: '{{ network_public_domain }}'
        - user: '{{ user_name_github }}'
          port: '{{ hostvars.server.port_ssh }}'
          key: '{{ config_dir }}/server_ssh_keys_{{ user_name_github }}'
          hosts:
            - host: '{{ hostvars.server.network_private_address }}'
            - host: '{{ hostvars.server.network_local_domain }}'
            - host: '{{ hostvars.server.network_public_sub_domain }}'
              name: '{{ network_public_domain }}'
    - role: config_wireguard_keys
      config_wireguard_keys:
        - '{{ config_dir }}/server_wireguard_keys_host'
        - '{{ config_dir }}/server_wireguard_keys_macbook'
        - '{{ config_dir }}/server_wireguard_keys_iphone'
    - role: config_wireguard_client
      config_wireguard_client_peer:
        address: '{{ hostvars.server.wireguard_address }}'
        public_domain: '{{ hostvars.server.network_public_sub_domain }}'
        port: '{{ hostvars.server.port_wireguard }}'
        key_pub: '{{ config_dir }}/server_wireguard_keys_host.pub'
        dns:
          - '{{ network_public_dns_1 }}'
          - '{{ network_public_dns_2 }}'
      config_wireguard_client_interfaces:
        - output: '{{ config_dir }}/wireguard_client_macbook'
          key: '{{ config_dir }}/server_wireguard_keys_macbook'
        - output: '{{ config_dir }}/wireguard_client_iphone'
          key: '{{ config_dir }}/server_wireguard_keys_iphone'
    - role: config_inventory
      config_inventory_output: '{{ config_dir }}/inventory_local_address'
      config_inventory_ssh_client: '{{ config_dir }}/ssh_client'
      config_inventory_user: '{{ user_name_regular }}'
      config_inventory_vars:
        - name: raspi
          host: '{{ hostvars.raspi.network_private_address }}'
        - name: server
          host: '{{ hostvars.server.network_private_address }}'
    - role: config_inventory
      config_inventory_output: '{{ config_dir }}/inventory_local_domain'
      config_inventory_ssh_client: '{{ config_dir }}/ssh_client'
      config_inventory_user: '{{ user_name_regular }}'
      config_inventory_vars:
        - name: raspi
          host: '{{ hostvars.raspi.network_local_domain }}'
        - name: server
          host: '{{ hostvars.server.network_local_domain }}'
    - role: config_inventory
      config_inventory_output: '{{ config_dir }}/inventory_public_domain'
      config_inventory_ssh_client: '{{ config_dir }}/ssh_client'
      config_inventory_user: '{{ user_name_regular }}'
      config_inventory_vars:
        - name: raspi
          host: '{{ hostvars.raspi.network_public_sub_domain }}'
        - name: server
          host: '{{ hostvars.server.network_public_sub_domain }}'
    - role: config_image_raspi
      config_image_raspi_output: '{{ config_dir }}/raspi_image'
      config_image_raspi_network_interface: '{{ hostvars.raspi.network_interface }}'
      config_image_raspi_network_hostname: '{{ hostvars.raspi.network_hostname }}'
      config_image_raspi_network_manual:
        address: '{{ hostvars.raspi.network_private_address }}'
        netmask: '{{ network_local_netmask }}'
        gateway: '{{ network_local_gateway }}'
        dns:
          - '{{ network_public_dns_1 }}'
          - '{{ network_public_dns_2 }}'
    - role: config_image_debian
      config_image_debian_ouput: '{{ config_dir }}/server_image'
      config_image_debian_hash_user_root: '{{ hash_root }}'
      config_image_debian_disk_system: '{{ hostvars.server.disk_system }}'
      config_image_debian_network_interface: '{{ hostvars.server.network_interface }}'
      config_image_debian_network_hostname: '{{ hostvars.server.network_hostname }}'
      config_image_debian_network_manual:
        address: '{{ hostvars.server.network_private_address }}'
        netmask: '{{ network_local_netmask }}'
        gateway: '{{ network_local_gateway }}'
        dns:
          - '{{ network_public_dns_1 }}'
          - '{{ network_public_dns_2 }}'
      config_image_debian_recipe_home: 16384
      config_image_debian_recipe_tmp: 16384
      config_image_debian_recipe_swap: 32768
