---

- name: Base
  hosts: raspi
  gather_facts: false
  become: true
  tags: base
  roles:
    - role: systemctl
      tags: systemctl
    - role: network
      tags: network
      network_interface: '{{ raspi_network_interface }}'
    - role: ssh
      tags: ssh
      ssh_port: '{{ raspi_ssh_port }}'
      ssh_key: raspi/ssh_keys_host
      ssh_key_pub: raspi/ssh_keys_host.pub
    - role: user
      tags: user
      user_name: root
      user_password: '{{ raspi_hash_user_root }}'
      user_shell: /bin/zsh
    - role: user
      tags: user
      user_id: '{{ user_regular_id }}'
      user_name: '{{ user_regular_name }}'
      user_password: '{{ raspi_hash_user_regular }}'
      user_key_pub: 'raspi/ssh_keys_{{ user_regular_name }}.pub'
      user_shell: /bin/zsh
      user_sudo: true
    - role: user
      tags: user
      user_id: '{{ user_ansible_id }}'
      user_name: '{{ user_ansible_name }}'
      user_password: '{{ raspi_hash_user_ansible }}'
      user_key_pub: 'raspi/ssh_keys_{{ user_ansible_name }}.pub'
      user_shell: /bin/zsh
      user_sudo: yes-no-password
    - role: ohmyzsh
      ohmyzsh_user_name: root
    - role: ohmyzsh
      ohmyzsh_user_name: '{{ user_regular_name }}'
    - role: ohmyzsh
      ohmyzsh_user_name: '{{ user_ansible_name }}'

- name: Pi Hole
  hosts: raspi
  gather_facts: false
  become: true
  tags: pihole
  roles:
    - role: pihole
      pihole_user_id: 1010
      pihole_password: '{{ raspi_hash_pihole }}'
      pihole_interface: '{{ raspi_network_interface }}'
      pihole_var: /mnt/data/pihole
      pihole_dns_1: '{{ network_dns_1 }}'
      pihole_dns_2: '{{ network_dns_2 }}'
