---

- name: Base
  hosts: raspi
  gather_facts: false
  become: true
  tags: base
  roles:
    - role: systemctl
      tags: systemctl
    - role: ssh
      tags: ssh
      ssh_port: '{{ port_ssh }}'
      ssh_key: raspi/ssh_keys_host
      ssh_key_pub: raspi/ssh_keys_host.pub
    - role: user
      tags: user
      user_name: root
      user_password: '{{ hash_root }}'
      user_shell: /bin/zsh
    - role: user
      tags: user
      user_id: '{{ user_id_regular }}'
      user_name: '{{ user_name_regular }}'
      user_password: '{{ hash_regular }}'
      user_key_pub: 'raspi/ssh_keys_{{ user_name_regular }}.pub'
      user_shell: /bin/zsh
      user_sudo_group: yes-no-password
    - role: ohmyzsh
      ohmyzsh_user_name: root
    - role: ohmyzsh
      ohmyzsh_user_name: '{{ user_name_regular }}'

- name: Node Exporter
  hosts: raspi
  gather_facts: false
  become: true
  tags: node_exporter
  roles:
    - role: node_exporter
  vars:
    node_exporter_address: '{{ network_private_address }}'
    node_exporter_port: '{{ port_node_exporter }}'

- name: Data Disks
  hosts: raspi
  gather_facts: false
  become: true
  tags: data
  roles:
    - role: lvm_vg
      tags: data
      lvm_vg_name: data
      lvm_vg_disks:
        - '{{ disk_1 }}'

- name: Installer
  hosts: raspi
  gather_facts: false
  become: true
  tags: installer
  roles:
    - role: installer
      installer_directory: infra
      installer_host: raspi
    - role: user
      tags: user
      user_id: '{{ user_id_github }}'
      user_name: '{{ user_name_github }}'
      user_password: '{{ hash_github }}'
      user_key_pub: 'raspi/ssh_keys_{{ user_name_github }}.pub'
      user_sudo_group: false
      user_sudo_commands:
        - /usr/lib/installer/run.sh *

- name: Pi Hole
  hosts: raspi
  gather_facts: false
  become: true
  tags: pihole
  roles:
    - role: lvm_lv
      vars:
        lvm_vg_name: data
        lvm_lv_name: pihole
        lvm_lv_size: 10G
    - role: pihole
      pihole_var: /mnt/data/pihole
      pihole_user_id: 1010
      pihole_password: '{{ hash_pihole }}'
      pihole_interface: '{{ network_interface }}'
      pihole_dns_1: '{{ network_public_dns_1 }}'
      pihole_dns_2: '{{ network_public_dns_2 }}'

- name: Local Network
  hosts: raspi
  gather_facts: false
  become: true
  tags: base
  roles:
    - role: network
      tags: network
      network_dns: ['{{ network_local_dns }}']
