---

- name: Base
  hosts: server
  gather_facts: false
  become: true
  tags: base
  roles:
    - role: systemctl
      tags: systemctl
    - role: cdrom
      tags: cdrom
    - role: keyboard
      tags: keyboard
    - role: network
      tags: network
      network_interface: '{{ server_network_interface }}'
    - role: apt
      tags: apt
    - role: grub
      tags: grub
    - role: ssh
      tags: ssh
      ssh_port: '{{ server_ssh_port }}'
      ssh_key: server/ssh_keys_host
      ssh_key_pub: server/ssh_keys_host.pub
    - role: user
      tags: user
      user_name: root
      user_password: '{{ server_hash_user_root }}'
      user_shell: /bin/zsh
    - role: user
      tags: user
      user_id: '{{ user_regular_id }}'
      user_name: '{{ user_regular_name }}'
      user_password: '{{ server_hash_user_regular }}'
      user_key_pub: 'server/ssh_keys_{{ user_regular_name }}.pub'
      user_shell: /bin/zsh
      user_sudo: yes-no-password
    - role: ohmyzsh
      ohmyzsh_user_name: root
    - role: ohmyzsh
      ohmyzsh_user_name: '{{ user_regular_name }}'

- name: Installer
  hosts: server
  gather_facts: false
  become: true
  tags: installer
  roles:
    - role: installer
      installer_directory: infra
      installer_host: server
    - role: user
      tags: user
      user_id: '{{ user_github_id }}'
      user_name: '{{ user_github_name }}'
      user_password: '{{ server_hash_user_github }}'
      user_key_pub: 'server/ssh_keys_{{ user_github_name }}.pub'
      user_sudo: false
      user_sudo_commands:
        - /usr/lib/installer/run.sh *

- name: Data Disks
  hosts: server
  gather_facts: false
  become: true
  tags: data
  roles:
    - role: mdadm
      mdadm_name: md0
      mdadm_level: 5
      mdadm_disks:
        - '{{ server_disk_1 }}'
        - '{{ server_disk_2 }}'
        - '{{ server_disk_3 }}'
    - role: lvm_vg
      vg_name: data
      vg_disks:
        - /dev/md0

- name: Wireguard
  hosts: server
  gather_facts: false
  become: true
  tags: wireguard
  roles:
    - role: wireguard
      wireguard_interface_name: wg0
      wireguard_interface_device: '{{ server_network_interface }}'
      wireguard_interface_ip_adress: '{{ server_wireguard_ip_adress }}'
      wireguard_interface_port: '{{ server_wireguard_port }}'
      wireguard_interface_key: server/wireguard_keys_host
      wireguard_peers:
        - name: macbook
          key_pub: server/wireguard_keys_macbook.pub
        - name: iphone
          key_pub: server/wireguard_keys_iphone.pub

- name: Time Machine
  hosts: server
  gather_facts: false
  become: true
  tags: timemachine
  roles:
    - role: lvm_lv
      tags: data
      vg_name: data
      lv_name: timemachine
      lv_size: 500G
      lv_opts: --type linear
    - role: samba
      samba_var: /mnt/data/timemachine
      samba_user: '{{ user_regular_name }}'
      samba_password: '{{ server_password_samba }}'
      samba_section: TimeMachine
      samba_section_conf: timemachine.conf.j2

- name: Media Softwares
  hosts: server
  gather_facts: false
  become: true
  tags: media
  roles:
    - role: lvm_lv
      tags: data
      vg_name: data
      lv_name: media
      lv_size: 15T
      lv_opts: --type linear
    - role: user_service
      tags: data
      user_service_id: '{{ server_user_media_id }}'
      user_service_name: '{{ server_user_media_name }}'
    - role: library
      tags: data
      library_user: '{{ server_user_media_name }}'
      library_var: /mnt/data/media/library
    - role: plex
      tags: plex
      plex_user: '{{ server_user_media_name }}'
      plex_var: /mnt/data/media/plex
    - role: qbittorrent
      tags: qbittorrent
      qbittorrent_name: '{{ server_qbittorrent_1_name }}'
      qbittorrent_port: '{{ server_qbittorrent_1_port }}'
      qbittorrent_var: '/mnt/data/media/{{ server_qbittorrent_1_name }}'
      qbittorrent_user: '{{ server_user_media_name }}'
      qbittorrent_peer_port: 50000
      qbittorrent_interface: '{{ server_network_interface }}'
      qbittorrent_address: '{{ server_network_local_ip_address }}'
    - role: joal
      tags: joal
      joal_user: '{{ server_user_media_name }}'
      joal_var: /mnt/data/media/joal
    - role: sabnzbd
      tags: sabnzbd
      sabnzbd_name: '{{ server_sabnzbd_1_name }}'
      sabnzbd_port: '{{ server_sabnzbd_1_port }}'
      sabnzbd_var: '/mnt/data/media/{{ server_sabnzbd_1_name }}'
      sabnzbd_user: '{{ server_user_media_name }}'
      sabnzbd_address: '{{ server_network_local_ip_address }}'
      sabnzbd_host_whitelist:
        - '{{ server_network_local_ip_address }}'
        - '{{ server_network_local_domain }}'
    - role: servarr
      tags: [servarr, prowlarr]
      servarr_software: prowlarr
      servarr_name: '{{ server_prowlarr_1_name }}'
      servarr_port: '{{ server_prowlarr_1_port }}'
      servarr_var: '/mnt/data/media/{{ server_prowlarr_1_name }}'
      servarr_user: '{{ server_user_media_name }}'
      servarr_address: '{{ server_network_local_ip_address }}'
    - role: jackett
      tags: jackett
      jackett_name: '{{ server_jackett_1_name }}'
      jackett_port: '{{ server_jackett_1_port }}'
      jackett_var: '/mnt/data/media/{{ server_jackett_1_name }}'
      jackett_user: '{{ server_user_media_name }}'
      jackett_external: true
      jackett_address: '{{ server_network_local_ip_address }}'
    - role: servarr
      tags: [servarr, radarr]
      servarr_software: radarr
      servarr_name: '{{ server_radarr_1_name }}'
      servarr_port: '{{ server_radarr_1_port }}'
      servarr_var: '/mnt/data/media/{{ server_radarr_1_name }}'
      servarr_user: '{{ server_user_media_name }}'
      servarr_address: '{{ server_network_local_ip_address }}'
    - role: servarr
      tags: [servarr, radarr]
      servarr_software: radarr
      servarr_name: '{{ server_radarr_2_name }}'
      servarr_port: '{{ server_radarr_2_port }}'
      servarr_var: '/mnt/data/media/{{ server_radarr_2_name }}'
      servarr_user: '{{ server_user_media_name }}'
      servarr_address: '{{ server_network_local_ip_address }}'
    - role: sonarr
      tags: sonarr
      sonarr_name: '{{ server_sonarr_1_name }}'
      sonarr_port: '{{ server_sonarr_1_port }}'
      sonarr_var: '/mnt/data/media/{{ server_sonarr_1_name }}'
      sonarr_user: '{{ server_user_media_name }}'
      sonarr_address: '{{ server_network_local_ip_address }}'
    - role: sonarr
      tags: sonarr
      sonarr_name: '{{ server_sonarr_2_name }}'
      sonarr_port: '{{ server_sonarr_2_port }}'
      sonarr_var: '/mnt/data/media/{{ server_sonarr_2_name }}'
      sonarr_user: '{{ server_user_media_name }}'
      sonarr_address: '{{ server_network_local_ip_address }}'

- name: Public Network
  hosts: server
  gather_facts: false
  become: true
  tags: public_network
  roles:
    - role: lvm_lv
      tags: [data, certbot]
      vg_name: data
      lv_name: certbot
      lv_size: 64M
      lv_opts: --type linear
    - role: certbot
      tags: certbot
      certbot_var: /mnt/data/certbot
      certbot_domain: '{{ network_public_domain }}'
      certbot_ovh_application_key: '{{ server_ovh_application_key }}'
      certbot_ovh_application_secret: '{{ server_ovh_application_secret }}'
      certbot_ovh_consumer_key: '{{ server_ovh_consumer_key }}'
    - role: ddclient
      tags: ddclient
      ddclient_login: '{{ server_ddclient_login }}'
      ddclient_password: '{{ server_ddclient_password }}'
      ddclient_domains: ['{{ network_public_domain }}']
