---

- name: Base
  hosts: server
  gather_facts: false
  become: true
  tags: base
  roles:
    - role: systemctl
      tags: systemctl
    - role: cdrom
      tags: cdrom
    - role: keyboard
      tags: keyboard
    - role: apt
      tags: apt
    - role: grub
      tags: grub
    - role: ssh
      tags: ssh
      ssh_port: '{{ port_ssh }}'
      ssh_key: server/ssh_keys_host
      ssh_key_pub: server/ssh_keys_host.pub
    - role: user
      tags: user
      user_name: root
      user_password: '{{ hash_root }}'
      user_shell: /bin/zsh
    - role: user
      tags: user
      user_id: '{{ user_id_regular }}'
      user_name: '{{ user_name_regular }}'
      user_password: '{{ hash_regular }}'
      user_key_pub: 'server/ssh_keys_{{ user_name_regular }}.pub'
      user_shell: /bin/zsh
      user_sudo_group: yes-no-password
    - role: ohmyzsh
      tags: user
      ohmyzsh_user_name: root
    - role: ohmyzsh
      tags: user
      ohmyzsh_user_name: '{{ user_name_regular }}'

- name: Installer
  hosts: server
  gather_facts: false
  become: true
  tags: installer
  roles:
    - role: installer
      installer_directory: infra
      installer_host: server
    - role: user
      tags: user
      user_id: '{{ user_id_github }}'
      user_name: '{{ user_name_github }}'
      user_password: '{{ hash_github }}'
      user_key_pub: 'server/ssh_keys_{{ user_name_github }}.pub'
      user_sudo_group: false
      user_sudo_commands:
        - /usr/lib/installer/run.sh *

- name: Data Disks
  hosts: server
  gather_facts: false
  become: true
  tags: data
  roles:
    - role: mdadm
      vars:
        mdadm_name: md0
        mdadm_level: 5
        mdadm_disks:
          - '{{ disk_1 }}'
          - '{{ disk_2 }}'
          - '{{ disk_3 }}'
    - role: lvm_vg
      tags: data
      vars:
        lvm_vg_name: data
        lvm_vg_disks:
          - /dev/md0

- name: Prometheus
  hosts: server
  gather_facts: false
  become: true
  tags: prometheus
  roles:
    - role: lvm_lv
      tags: data
      vars:
        lvm_vg_name: data
        lvm_lv_name: prometheus
        lvm_lv_size: 10G
    - role: prometheus
      vars:
        user_id: '{{ user_id_prometheus }}'
        prometheus_data: /mnt/data/prometheus
        prometheus_address: '{{ network_private_address }}'
        prometheus_port: '{{ port_prometheus }}'
        prometheus_retention_time: 90d
        prometheus_scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets:
                  - '{{ network_private_address }}:{{ port_prometheus }}'
          - job_name: node
            static_configs:
              - targets:
                  - '{{ network_private_address }}:{{ port_node_exporter }}'
                  - '{{ hostvars.raspi.network_private_address }}:{{ hostvars.raspi.port_node_exporter }}'

- name: Node Exporter
  hosts: server
  gather_facts: false
  become: true
  tags: node_exporter
  roles:
    - role: node_exporter
      vars:
        node_exporter_address: '{{ network_private_address }}'
        node_exporter_port: '{{ port_node_exporter }}'

- name: Grafana
  hosts: server
  gather_facts: false
  become: true
  tags: grafana
  roles:
    - role: lvm_lv
      tags: data
      vars:
        lvm_vg_name: data
        lvm_lv_name: grafana
        lvm_lv_size: 10G
    - role: grafana
      vars:
        grafana_data: /mnt/data/grafana
        grafana_admin_name: '{{ user_name_regular }}'
        grafana_admin_password: '{{ password_grafana }}'
        grafana_address: '{{ network_private_address }}'
        grafana_port: '{{ port_grafana }}'

- name: Wireguard
  hosts: server
  gather_facts: false
  become: true
  tags: wireguard
  roles:
    - role: wireguard
      wireguard_interface_name: wg0
      wireguard_interface_device: '{{ network_interface }}'
      wireguard_interface_address: '{{ wireguard_address }}'
      wireguard_interface_port: '{{ port_wireguard }}'
      wireguard_interface_key: server/wireguard_keys_host
      wireguard_peers:
        - name: macbook
          key_pub: server/wireguard_keys_macbook.pub
        - name: iphone
          key_pub: server/wireguard_keys_iphone.pub

- name: Samba
  hosts: server
  gather_facts: false
  become: true
  tags: samba
  roles:
    - role: lvm_lv
      tags: data
      vars:
        lvm_vg_name: data
        lvm_lv_name: timemachine
        lvm_lv_size: 500G
    - role: lvm_lv
      tags: data
      vars:
        lvm_vg_name: data
        lvm_lv_name: share
        lvm_lv_size: 10G
    - role: samba
      vars:
        samba_address: '{{ network_private_address }}'
        samba_users:
          - name: '{{ user_name_regular }}'
            password: '{{ password_samba }}'
        samba_shares:
          - name: TimeMachine
            timemachine: true
            path: /mnt/data/timemachine
            users:
              - '{{ user_name_regular }}'
          - name: Share
            path: /mnt/data/share
            users:
              - '{{ user_name_regular }}'

- name: Media Softwares
  hosts: server
  gather_facts: false
  become: true
  tags: media
  roles:
    - role: lvm_lv
      tags: data
      vars:
        lvm_vg_name: data
        lvm_lv_name: media
        lvm_lv_size: 15T
    - role: user
      tags: [data, user]
      user_system: true
      user_id: '{{ user_id_media }}'
      user_name: '{{ user_name_media }}'
    - role: library
      tags: data
      library_user: '{{ user_name_media }}'
      library_var: /mnt/data/media/library
    - role: plex
      tags: plex
      plex_user: '{{ user_name_media }}'
      plex_var: /mnt/data/media/plex
    - role: qbittorrent
      tags: qbittorrent
      qbittorrent_name: qbittorrent
      qbittorrent_port: '{{ port_qbittorrent }}'
      qbittorrent_var: /mnt/data/media/qbittorrent
      qbittorrent_user: '{{ user_name_media }}'
      qbittorrent_peer_port: 50000
      qbittorrent_interface: '{{ network_interface }}'
      qbittorrent_address: '{{ network_private_address }}'
    - role: joal
      tags: joal
      joal_user: '{{ user_name_media }}'
      joal_var: /mnt/data/media/joal
    - role: sabnzbd
      tags: sabnzbd
      sabnzbd_name: sabnzbd
      sabnzbd_port: '{{ port_sabnzbd }}'
      sabnzbd_var: /mnt/data/media/sabnzbd
      sabnzbd_user: '{{ user_name_media }}'
      sabnzbd_address: '{{ network_private_address }}'
      sabnzbd_host_whitelist:
        - '{{ network_private_address }}'
        - '{{ network_local_domain }}'
    - role: servarr
      tags: [servarr, prowlarr]
      servarr_software: prowlarr
      servarr_name: prowlarr
      servarr_port: '{{ port_prowlarr }}'
      servarr_var: /mnt/data/media/prowlarr
      servarr_user: '{{ user_name_media }}'
      servarr_address: '{{ network_private_address }}'
    - role: servarr
      tags: [servarr, radarr]
      servarr_software: radarr
      servarr_name: radarr-1
      servarr_port: '{{ port_radarr_1 }}'
      servarr_var: /mnt/data/media/radarr-1
      servarr_user: '{{ user_name_media }}'
      servarr_address: '{{ network_private_address }}'
    - role: servarr
      tags: [servarr, radarr]
      servarr_software: radarr
      servarr_name: radarr-2
      servarr_port: '{{ port_radarr_2 }}'
      servarr_var: /mnt/data/media/radarr-2
      servarr_user: '{{ user_name_media }}'
      servarr_address: '{{ network_private_address }}'
    - role: sonarr
      tags: sonarr
      sonarr_name: sonarr-1
      sonarr_port: '{{ port_sonarr_1 }}'
      sonarr_var: /mnt/data/media/sonarr-1
      sonarr_user: '{{ user_name_media }}'
      sonarr_address: '{{ network_private_address }}'
    - role: sonarr
      tags: sonarr
      sonarr_name: sonarr-2
      sonarr_port: '{{ port_sonarr_2 }}'
      sonarr_var: /mnt/data/media/sonarr-2
      sonarr_user: '{{ user_name_media }}'
      sonarr_address: '{{ network_private_address }}'

- name: Jackett
  hosts: server
  gather_facts: false
  become: true
  tags: jackett
  roles:
    - role: jackett
      vars:
        user_id: '{{ user_id_media }}'
        user_name: '{{ user_name_media }}'
        jackett_data: /mnt/data/media/jackett
        jackett_address: '{{ network_private_address }}'
        jackett_port: '{{ port_jackett }}'
        jackett_key: '{{ password_jackett_key }}'
        jackett_id: '{{ password_jackett_key }}'

- name: Public Network
  hosts: server
  gather_facts: false
  become: true
  tags: public_network
  roles:
    - role: lvm_lv
      tags: [data, certbot]
      vars:
        lvm_vg_name: data
        lvm_lv_name: certbot
        lvm_lv_size: 64M
    - role: certbot
      tags: certbot
      certbot_var: /mnt/data/certbot
      certbot_domain: '{{ network_public_domain }}'
      certbot_ovh_application_key: '{{ bitwarden_ovh_application_key }}'
      certbot_ovh_application_secret: '{{ bitwarden_ovh_application_secret }}'
      certbot_ovh_consumer_key: '{{ bitwarden_ovh_application_consumer_key }}'
    - role: ddclient
      tags: ddclient
      ddclient_login: '{{ bitwarden_ovh_dns_username }}'
      ddclient_password: '{{ bitwarden_ovh_dns_password }}'
      ddclient_domains: ['{{ network_public_domain }}']

- name: Local Network
  hosts: server
  gather_facts: false
  become: true
  tags: base
  roles:
    - role: network
      tags: network
      network_dns: ['{{ network_local_dns }}']
