# Install package

- name: Package
  ansible.builtin.apt:
    name:
      - zsh
      - git
    state: present

# Download

- name: Git clone
  ansible.builtin.git:
    repo: '{{ ohmyzsh_git }}'
    dest: '~{{ ohmyzsh_user_name }}/.oh-my-zsh'
    version: '{{ ohmyzsh_version }}'
  become_user: '{{ ohmyzsh_user_name }}'

# Configure

- name: Create config
  ansible.builtin.template:
    src: zshrc.j2
    dest: '~{{ ohmyzsh_user_name }}/.zshrc'
    owner: '{{ ohmyzsh_user_name }}'
    group: '{{ ohmyzsh_user_name }}'
    mode: u=rw,go=r

- name: Set shell
  ansible.builtin.user:
    name: '{{ ohmyzsh_user_name }}'
    shell: /bin/zsh
