jackett_name: jackett
jackett_version: 0.21.950
jackett_archive: 'https://github.com/Jackett/Jackett/releases/download/v{{ jackett_version }}/Jackett.Binaries.LinuxAMDx64.tar.gz'
jackett_lib: '/usr/lib/jackett-{{ jackett_version }}'
jackett_var: '/var/lib/{{ jackett_name }}'
jackett_user: '{{ jackett_name }}'
jackett_port: 8080
jackett_address: 127.0.0.1
jackett_external: false
jackett_config:
  LocalBindAddress: '{{ jackett_address }}'
  AllowExternal: '{{ jackett_external }}'
  Port: '{{ jackett_port }}'
