# Install package

- name: Package
  apt:
    name: default-jre
    state: latest

# Create lib

- name: Create lib directory
  file:
    path: '{{ joal_lib }}'
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Create lib
  unarchive:
    src: '{{ joal_archive }}'
    remote_src: yes
    dest: '{{ joal_lib }}'
    owner: root
    group: root
    mode: u+rw,go-w+r
    creates: '{{ joal_lib }}/jack-of-all-trades-{{ joal_version }}.jar'
  register: create_lib

# Create var

- name: Create var directory
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ joal_user }}'
    group: '{{ joal_user }}'
    mode: ug=rwx,o=rx
  with_items:
  - '{{ joal_var }}'
  - '{{ joal_var }}/clients'
  - '{{ joal_var }}/torrents'
  - '{{ joal_var }}/torrents/archived'

- name: Create client config
  copy:
    src: '{{ joal_lib }}/clients/{{ joal_client }}.client'
    remote_src: yes
    dest: '{{ joal_var }}/clients/{{ joal_client }}.client'
    owner: '{{ joal_user }}'
    group: '{{ joal_user }}'
    mode: ug=rw,o=r
  register: create_client_config

- name: Create config
  template:
    src: config.json.j2
    dest: '{{ joal_var }}/config.json'
    owner: '{{ joal_user }}'
    group: '{{ joal_user }}'
    mode: ug=rw,o=r
  register: create_config

- name: Fix permissions
  shell: >
    find {{ joal_var }} \
      ! -user root \
      ! -user {{ joal_user }} \
      -print \
      -exec chown {{ joal_user }}. {} \; \
      | wc -l
  register: fix_permissions
  changed_when: fix_permissions.stdout != '0'

# Create service

- name: Create service
  template:
    src: service.j2
    dest: '/etc/systemd/system/{{ joal_name }}.service'
    owner: root
    group: root
    mode: u=rw,go=r
  register: create_service

- name: Enable
  systemd: 
    name: '{{ joal_name }}'
    enabled: true

- name: Restart
  systemd:
    name: '{{ joal_name }}'
    state: restarted
    daemon_reload: true
  when: >
    create_lib is changed or
    create_client_config is changed or
    create_config is changed or
    create_service is changed

- name: Start 
  systemd: 
    name: '{{ joal_name }}'
    state: started
