# Apt source

- name: Package gpg
  ansible.builtin.apt:
    name: gpg
    state: present

- name: GPG key
  ansible.builtin.get_url:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    dest: /etc/apt/trusted.gpg.d/plex.asc
    force: false
    owner: root
    group: root
    mode: ug=rw,o=r

- name: Add apt source
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/plex.asc] https://downloads.plex.tv/repo/deb public main
    filename: plex
    update_cache: true

# Create var

- name: Create var directory
  ansible.builtin.file:
    path: '{{ plex_var }}'
    state: directory
    owner: '{{ plex_user }}'
    group: '{{ plex_user }}'
    mode: ug=rwx,o=rx

- name: Fix permissions
  ansible.builtin.shell: >
    set -e -o pipefail
    find {{ plex_var }} \
      ! -user root \
      ! -user {{ plex_user }} \
      -print \
      -exec chown {{ plex_user }}. {} \; \
      | wc -l
  register: fix_permissions
  changed_when: fix_permissions.stdout != '0'
  tags: fix_permissions

# Create service override

- name: Create service directory
  ansible.builtin.file:
    path: /etc/systemd/system/plexmediaserver.service.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Create service
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/plexmediaserver.service.d/override.conf
    owner: root
    group: root
    mode: u=rw,go=r
  register: create_service

# Install package

- name: Package
  ansible.builtin.apt:
    name: "plexmediaserver={{ plex_version }}"
    update_cache: true
  register: package

- name: Remove default plex user
  ansible.builtin.user:
    name: plex
    state: absent
    remove: true
  when: plex_user != 'plex'

# Start service

- name: Enable
  ansible.builtin.systemd:
    name: plexmediaserver
    enabled: true

- name: Restart
  ansible.builtin.systemd:
    name: plexmediaserver
    state: restarted
    daemon_reload: true
  when: >
    create_service is changed or
    package is changed

- name: Start
  ansible.builtin.systemd:
    name: plexmediaserver
    state: started
