- name: Set default
  ansible.builtin.shell: >
    set -e -o pipefail
    && [ "$(systemctl get-default)" = multi-user.target ]
    || (systemctl set-default multi-user.target && echo CHANGED)
  args:
    executable: /bin/bash
  register: set_default
  changed_when: '"CHANGED" in set_default.stdout'
