- name: Create inventory dir
  ansible.builtin.file:
    path: '{{ config_dir }}/inventory'
    state: directory

- name: Create inventory
  ansible.builtin.copy:
    content: >
      host ansible_connection=ssh ansible_ssh_host="{{ item }}"
      ansible_ssh_extra_args="-F {{ config_dir}}/ssh/config"
      ansible_user={{ config_inventory_user }}
    dest: '{{ config_dir }}/inventory/{{ item }}'
  with_items: '{{ config_inventory_domains }}'
