- name: Create inventory
  ansible.builtin.copy:
    content: |
      {% for var in config_inventory_vars -%}
      {{ var.name }} ansible_connection=ssh ansible_ssh_host="{{ var.host }}" ansible_ssh_extra_args="-F {{ config_inventory_ssh_client }}" ansible_user={{ config_inventory_user }}
      {% endfor %}
    dest: '{{ config_inventory_output }}'
