# Install package

- name: Package
  ansible.builtin.apt:
    name: ddclient
    state: present
    policy_rc_d: 101

# Create config

- name: Create config
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
    owner: root
    group: root
    mode: u=rw,go=
  no_log: true
  register: create_config

# Create service

- name: Enable
  ansible.builtin.systemd:
    name: ddclient
    enabled: true

- name: Restart
  ansible.builtin.systemd:
    name: ddclient
    state: restarted
    daemon_reload: true
  when: create_config is changed

- name: Start
  ansible.builtin.systemd:
    name: ddclient
    state: started
