---

arch: amd64

user_id_prometheus: 900
user_id_grafana: 901
user_id_media: 1012

user_name_media: media

network_private_address: 192.168.100.3
network_hostname: server
network_interface: enp0s31f6
network_local_domain: '{{ network_hostname }}.local'
network_public_sub_domain: '{{ network_hostname }}.{{ network_public_domain }}'

wireguard_address: 10.0.100

disk_system: /dev/disk/by-id/nvme-KINGSTON_SNV2S500G_50026B7685F960D0
disk_1: /dev/disk/by-id/ata-ST10000NT001-3LY101_WWY07EXB
disk_2: /dev/disk/by-id/ata-ST10000NT001-3LY101_WP0023PL
disk_3: /dev/disk/by-id/ata-ST10000NT001-3LY101_WP012NTN

port_ssh: 23
port_wireguard: 51820
port_prometheus: 9000
port_node_exporter: 9001
port_grafana: 9002
port_qbittorrent: 8010
port_sabnzbd: 8020
port_prowlarr: 8031
port_jackett: 8041
port_radarr_1: 8051
port_radarr_2: 8052
port_sonarr_1: 8061
port_sonarr_2: 8062
