---

- name: Base
  hosts: virtual
  gather_facts: false
  become: true
  tags: base
  roles:
    - role: systemctl
      tags: systemctl
    - role: cdrom
      tags: cdrom
    - role: keyboard
      tags: keyboard
    - role: network
      tags: network
    - role: apt
      tags: apt
    - role: grub
      tags: grub
    - role: ssh
      tags: ssh
      ssh_key: virtual/ssh_keys_host
      ssh_key_pub: virtual/ssh_keys_host.pub
    - role: user
      tags: user
      user_name: root
      user_password: '{{ virtual_hash_user_root }}'
      user_shell: /bin/zsh
    - role: user
      tags: user
      user_name: '{{ user_name_regular }}'
      user_password: '{{ virtual_hash_user_regular }}'
      user_key_pub: 'virtual/ssh_keys_{{ user_name_regular }}.pub'
      user_shell: /bin/zsh
      user_sudo_group: yes-no-password
    - role: ohmyzsh
      ohmyzsh_user_name: root
    - role: ohmyzsh
      ohmyzsh_user_name: '{{ user_name_regular }}'
