# Install Package

- name: Package
  ansible.builtin.apt:
    name: make
    state: present

# Create lib

- name: Create lib directory
  ansible.builtin.file:
    path: '{{ unrar_lib }}'
    state: directory
    owner: root
    group: root
    mode: ug=rwx,o=rx

- name: Create lib
  ansible.builtin.unarchive:
    src: '{{ unrar_archive }}'
    remote_src: true
    dest: '{{ unrar_lib }}'
    creates: '{{ unrar_lib }}/makefile'
    extra_opts:
      - --transform
      - 's/^unrar//'

- name: Build lib
  ansible.builtin.shell: |
    make -j 8
    make install
  args:
    chdir: '{{ unrar_lib }}'
    creates: '{{ unrar_lib }}/unrar'
