qbittorrent_name: qbittorrent
qbittorrent_version: 4.5.2-3+deb12u1
qbittorrent_var: '/var/lib/{{ qbittorrent_name }}'
qbittorrent_address: 127.0.0.1
qbittorrent_port: 8080
qbittorrent_peer_port: 50000
qbittorrent_interface: enp0s1
qbittorrent_config:
  - [AutoRun, enabled, false]
  - [BitTorrent, Session\BTProtocol, TCP]
  - [BitTorrent, Session\DisableAutoTMMByDefault, false]
  - [BitTorrent, Session\DisableAutoTMMTriggers\CategorySavePathChanged, false]
  - [BitTorrent, Session\DisableAutoTMMTriggers\DefaultSavePathChanged, false]
  - [Core, AutoDeleteAddedTorrentFile, IfAdded]
  - [LegalNotice, Accepted, true]
  - [Preferences, Bittorrent\MaxRatio, 0]
  - [Preferences, Connection\PortRangeMin, '{{ qbittorrent_peer_port }}']
  - [Preferences, Connection\UPnP, false]
  - [Preferences, Connection\Interface, '{{ qbittorrent_interface }}']
  - [Preferences, Connection\InterfaceName, '{{ qbittorrent_interface }}']
  - [Preferences, Connection\InterfaceAddress, 0.0.0.0]
  - [Preferences, Downloads\PreAllocation, true]
  - [Preferences, WebUI\Address, '{{ qbittorrent_address }}']
  - [Preferences, WebUI\Port, '{{ qbittorrent_port }}']
  - [Preferences, WebUI\AuthSubnetWhitelistEnabled, true]
  - [Preferences, WebUI\AuthSubnetWhitelist, 0.0.0.0/0]
  - [Preferences, WebUI\CSRFProtection, false]
  - [Preferences, WebUI\ClickjackingProtection, false]
