---

- name: 'Directories are owned by user "{{ chown_user_name }}"'
  loop: '{{ chown_paths }}'
  loop_control:
    label: 'Directory "{{ item }}" is owned by user "{{ chown_user_name }}"'
  ansible.builtin.shell: |
    set -e -o pipefail
    find "{{ item }}" \
      ! -user root ! -group root \
      ! -user {{ chown_user_name }} ! -group {{ chown_user_name }} \
      -print \
    {% if not ansible_check_mode %}
      -exec chown {{ chown_user_name }}:{{ chown_user_name }} {} \; \
    {% endif %}
    | wc -l
  args:
    executable: /bin/bash
  check_mode: false
  register: __chown_output
  changed_when: __chown_output.stdout != "0"
  notify: '{{ chown_notify | default(omit) }}'
