---

__grafana_bin: '{{ service_opt }}/bin-{{ grafana_version }}'
__grafana_etc: '{{ service_opt }}/etc'
__grafana_run: '{{ service_opt }}/run'

service_packages:
  - ca-certificates
  - adduser
  - libfontconfig1
  - musl
service_config:
  - ExecStart: |
      {{ __grafana_bin }}/bin/grafana server \
        --homepath={{ __grafana_bin }} \
        --config={{ __grafana_etc }}/grafana.ini \
        --pidfile={{ __grafana_run }}/pid
service_readonly:
  - '{{ __grafana_bin }}'
  - '{{ __grafana_etc }}'
service_readwrite:
  - '{{ __grafana_run }}'
  - '{{ grafana_data }}'
