---

grafana_var_dir: '{{ lvm_vg is defined | ternary(service_mounts[0], service_var_dir) }}'

service_name: grafana
service_chroot: true
service_packages:
  - ca-certificates
  - adduser
  - libfontconfig1
  - musl
service_config:
  Service:
    ExecStart: |
      {{ service_lib_dir }}/{{ archive_name }}/bin/grafana server \
        --homepath={{ service_lib_dir }}/{{ archive_name }} \
        --config={{ service_etc_dir }}/grafana.ini \
        --pidfile={{ service_run_dir }}/pid
service_lvs:
  - name: data
    size: '{{ grafana_lv_size }}'

archive_url:
  "https://dl.grafana.com/oss/release/\
   grafana-{{ grafana_version }}.linux-amd64.tar.gz"
archive_name: bin
archive_version: '{{ grafana_version }}'
archive_transform: 'grafana-{{ grafana_version }}'
