---

service_name: grafana
service_chroot: true
service_packages:
  - ca-certificates
  - adduser
  - libfontconfig1
  - musl
service_exec_start: |
  {{ service_lib }}/current/bin/grafana server \
    --homepath={{ service_lib }}/current \
    --config={{ service_etc }}/grafana.ini \
    --pidfile={{ service_run }}/pid

archive_url:
  "https://dl.grafana.com/oss/release/\
   grafana-{{ grafana_version }}.linux-amd64.tar.gz"
archive_version: '{{ grafana_version }}'
archive_transform: 'grafana-{{ grafana_version }}'
