- name: Create directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ library_user }}'
    group: '{{ library_user }}'
    mode: ug=rwx,o=rx
  with_items:
    - '{{ library_var }}'
    - '{{ library_var }}/radarr-1'
    - '{{ library_var }}/radarr-2'
    - '{{ library_var }}/sonarr-1'
    - '{{ library_var }}/sonarr-2'

- name: Fix permissions
  ansible.builtin.include_role:
    name: fix_permissions
  vars:
    fix_permissions_dir: '{{ library_var }}'
    fix_permissions_user: '{{ library_user }}'
