- name: Config
  hosts: localhost
  gather_facts: false
  roles:
    - role: config
      config_password:
        - var: user_root_password
        - var: user_regular_password
        - var: user_ansible_password
        - var: samba_password
        - var: pihole_password
      config_hash:
        - var: user_root_password
          method: crypt
        - var: user_regular_password
          method: crypt
        - var: user_ansible_password
          method: crypt
        - var: pihole_password
          method: sha256
      config_ssh:
        users:
          - '{{ user_regular_name }}'
          - '{{ user_ansible_name }}'
        domains:
          - '{{ network_domain_local }}'
          - '{{ network_domain_public }}'
      config_inventory:
        user: '{{ user_ansible_name }}'
        domains:
          - '{{ network_domain_local }}'
          - '{{ network_domain_public }}'
      config_image:
        root_password: '{{ hash_user_root_password }}'
        disk_system: '{{ disk_system }}'
        network_interface: '{{ network_interface }}'
        network_hostname: '{{ network_hostname }}'
        network_manual:
          address: '{{ network_ip_address }}'
          netmask: '{{ network_netmask }}'
          gateway: '{{ network_gateway }}'
          dns: ['{{ dns_1 }}', '{{ dns_2 }}']
        recipe_home: 16384
        recipe_tmp: 16384
        recipe_swap: 32768
