---

name: nix-shell

inputs:
  command:
    required: true

runs:
  using: composite
  steps:
    - name: install
      uses: nixbuild/nix-quick-install-action@v24
    - uses: nix-community/cache-nix-action@v4
      with:
        key: nix-cache-${{ hashFiles('**/*.nix') }}
        restore-keys: nix-cache-
        gc-linux: true
        gc-max-store-size-linux: 1000000000
        purge: true
        purge-keys: nix-cache-
        purge-created: true
        purge-created-max-age: 604800
    - name: run
      run: nix-shell --command "${{ inputs.command }}"
      shell: bash
