# Config

- name: Create config
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: u=rw,go=r
  register: create_config

# Start service

- name: Enable
  ansible.builtin.systemd:
    name: networking
    enabled: true

- name: Restart
  ansible.builtin.systemd:
    name: networking
    state: restarted
    daemon_reload: true
  when: >
    create_config is changed

- name: Start
  ansible.builtin.systemd:
    name: networking
    state: started

# Package

- name: Package
  ansible.builtin.apt:
    name: libnss-mdns
    state: present
