user_name: david
network_interface: enp0s31f6
network_host_name: server
private_domain: server.local
public_domain: server.davidlsq.fr

qbittorrent_1_name: qbittorrent
qbittorrent_1_port: 8010

sabnzbd_1_name: sabnzbd
sabnzbd_1_port: 8020

prowlarr_1_name: prowlarr
prowlarr_1_port: 8031

jackett_1_name: jackett
jackett_1_port: 8041

radarr_1_name: radarr-1
radarr_1_port: 8051

radarr_2_name: radarr-2
radarr_2_port: 8052

sonarr_1_name: sonarr-1
sonarr_1_port: 8061

sonarr_2_name: sonarr-2
sonarr_2_port: 8062
