# Install package

- name: Package
  ansible.builtin.apt:
    name: lvm2
    state: present

# Create VG

- name: Create
  community.general.lvg:
    vg: '{{ vg_name }}'
    pesize: 64
    pvs: '{{ vg_disks | join(",") }}'
