---

- name: Install package "debootstrap"
  ansible.builtin.apt:
    name: debootstrap
    state: present

- name: 'Chroot "{{ chroot_path }}" exists'
  ansible.builtin.command: >
    debootstrap bookworm "{{ chroot_path }}"
  args:
    creates: '{{ chroot_path }}'

- name: 'Chroot "{{ chroot_path }}" has its packages installed'
  when: chroot_packages is defined
  vars:
    packages: '{{ chroot_packages | join(" ") }}'
  ansible.builtin.shell: |
    set -e -o pipefail
    if ! chroot "{{ chroot_path }}" dpkg -s {{ packages }}; then
    {% if not ansible_check_mode %}
      chroot "{{ chroot_path }}" apt-get install -y {{ packages }}
    {% endif %}
      echo CHANGED
    fi
  args:
    executable: /bin/bash
  check_mode: false
  register: __chroot_package_output
  changed_when: >
    __chroot_package_output.stdout_lines | last | default == "CHANGED"
  notify: '{{ chroot_notify | default(omit) }}'
