# Install package

- name: Package apt
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-venv
    state: present

# Create lib

- name: Create venv
  ansible.builtin.pip:
    name:
      - certbot
      - certbot-dns-ovh
    virtualenv: '{{ certbot_venv }}'
    virtualenv_command: python3 -m venv
  register: create_venv

# Create var

- name: Create var directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx
  with_items:
    - '{{ certbot_var }}'
    - '{{ certbot_var }}/config'
    - '{{ certbot_var }}/work'

- name: Create config
  ansible.builtin.template:
    src: ovh-credentials.conf.j2
    dest: '{{ certbot_ovh_credentials }}'
    owner: root
    group: root
    mode: u=rw,go=
  no_log: true
  register: create_config

- name: Create script
  ansible.builtin.template:
    src: certbot.sh.j2
    dest: '{{ certbot_script }}'
    owner: root
    group: root
    mode: u=rwx,go=r
  register: create_config

# Create certificate

- name: Init certificate
  ansible.builtin.command: '{{ certbot_script }}'
  args:
    creates: '{{ certbot_var }}/config/live/{{ certbot_domain }}/fullchain.pem'

- name: Add cron
  ansible.builtin.cron:
    name: 'certbot-{{ item }}'
    special_time: '{{ item }}'
    job: '{{ certbot_script }}'
  with_items:
    - 'monthly'
    - 'reboot'
