---

service_unit_file: '/etc/systemd/system/{{ service_name }}.service'
service_unit_dir: '{{ service_unit_file }}.d'
service_opt_dir: '/opt/{{ service_name }}'
service_lib_dir: '{{ service_opt_dir }}/lib'
service_etc_dir: '{{ service_opt_dir }}/etc'
service_run_dir: '{{ service_opt_dir }}/run'
service_var_dir: '{{ service_opt_dir }}/var'
service_log_dir: '{{ service_opt_dir }}/log'
service_chroot_dir: '{{ service_opt_dir }}/chroot'
service_lvs: []
service_mounts: '{{ lvm_lvs | map(attribute="mount") }}'

lvm_lvs: |
  {% set result = [] %}
  {% for lv in service_lvs %}
  {% set _ = result.append({
    "name": service_name + "-" + lv.name,
    "size": lv.size,
    "mount": "/mnt/" + lvm_vg + "/" + service_name + "/" + lv.name
  }) %}
  {% endfor %}
  {{ result }}
