# Package

- name: Package
  ansible.builtin.apt:
    name: systemd-resolved
    state: present

# Setup networkd

- name: Create directory
  ansible.builtin.file:
    path: /etc/systemd/network
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Create service
  ansible.builtin.template:
    src: network.j2
    dest: /etc/systemd/network/interface.network
    owner: root
    group: root
    mode: u=rw,go=r
  register: create_service

- name: Enable
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true

- name: Restart
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: true
  when: create_service is changed

- name: Start
  ansible.builtin.systemd:
    name: systemd-networkd
    state: started

# Setup resolved

- name: Config hostname
  ansible.builtin.copy:
    content: '{{ network_host_name }}'
    dest: /etc/hostname
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: config_hostname

- name: Set hostname with systemd
  ansible.builtin.hostname:
    name: '{{ network_host_name }}'
    use: systemd

- name: Set config link
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: Enable
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true

- name: Restart
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
  when: config_hostname is changed

- name: Start
  ansible.builtin.systemd:
    name: systemd-resolved
    state: started
