- name: Create dir
  ansible.builtin.file:
    path: '{{ config_dir }}/image'
    state: directory

- name: Create preseed config
  ansible.builtin.template:
    src: image/preseed.cfg.j2
    dest: '{{ config_dir }}/image/preseed.cfg'
  no_log: true

- name: Create recipe
  ansible.builtin.template:
    src: image/recipe.j2
    dest: '{{ config_dir }}/image/recipe'

- name: Create grub config
  ansible.builtin.copy:
    src: image/grub.cfg
    dest: '{{ config_dir }}/image/grub.cfg'

- name: Create playbook script
  ansible.builtin.copy:
    src: image/playbook.sh
    dest: '{{ config_dir }}/image/playbook.sh'

- name: Create install script
  ansible.builtin.copy:
    src: image/install.sh
    dest: '{{ config_dir }}/image/install.sh'
