---

- name: Include "archive" role
  ansible.builtin.include_role:
    name: archive
  vars:
    archive_url:
      "https://github.com/Jackett/Jackett/releases/download/v{{ jackett_version }}/\
       Jackett.Binaries.LinuxAMDx64.tar.gz"
    archive_dest: '{{ service_opt }}/bin-{{ jackett_version }}.tar.gz'
    archive_content: '{{ __jackett_bin }}'
    archive_creates: '{{ __jackett_bin }}/jackett'
    archive_transform: Jackett

- name: 'Config "{{ __jackett_etc }}/ServerConfig.json" exists'
  ansible.builtin.template:
    src: ServerConfig.json.j2
    dest: '{{ __jackett_etc }}/ServerConfig.json'
    owner: root
    group: root
    mode: u=rw,go=r
  notify: service restart

- name: 'Config "{{ __jackett_etc }}/config.sh" exists'
  ansible.builtin.template:
    src: config.sh.j2
    dest: '{{ __jackett_etc }}/config.sh'
    owner: root
    group: root
    mode: u=rwx,go=rx
  notify: service restart
