---

dependencies:
  - role: lvm
    when: prometheus_vg is defined
    vars:
      lvm_vg: '{{ prometheus_vg }}'
      lvm_lvs:
        - name: '{{ service_name }}'
          size: '{{ prometheus_lv_size }}'
          mount: '{{ service_var }}'
  - role: service
  - role: archive
