---

- name: 'Config "{{ service_etc_dir }}/prometheus.yml" exists'
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: '{{ service_etc_dir }}/prometheus.yml'
    owner: root
    group: root
    mode: u=rw,go=r
  notify: service reload
