- name: Config
  hosts: localhost
  gather_facts: false
  roles:
    - role: config_password
      config_password:
        - var: user_root_password
        - var: user_regular_password
        - var: user_ansible_password
        - var: pihole_password
    - role: config_hash
      config_hash:
        - var: user_root_password
          method: crypt
        - var: user_regular_password
          method: crypt
        - var: user_ansible_password
          method: crypt
        - var: pihole_password
          method: sha256
    - role: config_ssh
      config_ssh_users:
        - '{{ user_regular_name }}'
        - '{{ user_ansible_name }}'
      config_ssh_domains:
        - '{{ network_domain_local }}'
    - role: config_inventory
      config_inventory_user: '{{ user_ansible_name }}'
      config_inventory_domains:
        - '{{ network_domain_local }}'
    - role: config_raspi
      config_raspi_network_hostname: '{{ network_hostname }}'
