- name: Base
  hosts: host
  gather_facts: false
  become: true
  tags: base
  roles:
    - role: systemctl
      tags: systemctl
    - role: network
      tags: network
    - role: ssh_server
      tags: ssh_server
      ssh_server_key: ssh/host
      ssh_server_key_pub: ssh/host.pub
    - role: user
      tags: user
      user_name: root
      user_password: '{{ hash_user_root_password }}'
      user_shell: /bin/zsh
    - role: user
      tags: user
      user_id: '{{ user_regular_id }}'
      user_name: '{{ user_regular_name }}'
      user_password: '{{ hash_user_regular_password }}'
      user_key_pub: 'ssh/{{ user_regular_name }}.pub'
      user_shell: /bin/zsh
      user_sudo: true
    - role: user
      tags: user
      user_id: '{{ user_ansible_id }}'
      user_name: '{{ user_ansible_name }}'
      user_password: '{{ hash_user_ansible_password }}'
      user_key_pub: 'ssh/{{ user_ansible_name }}.pub'
      user_shell: /bin/zsh
      user_sudo: yes-no-password
    - role: ohmyzsh
      ohmyzsh_user_name: root
    - role: ohmyzsh
      ohmyzsh_user_name: '{{ user_regular_name }}'
    - role: ohmyzsh
      ohmyzsh_user_name: '{{ user_ansible_name }}'

- name: Pi Hole
  hosts: host
  gather_facts: false
  become: true
  tags: pihole
  roles:
    - role: pihole
      pihole_user_id: 1010
      pihole_password: '{{ hash_pihole_password }}'
      pihole_interface: '{{ network_interface }}'
      pihole_var: /mnt/data/pihole
      pihole_dns_1: '{{ dns_1 }}'
      pihole_dns_2: '{{ dns_2 }}'
