- name: Create user with id
  when: user_service_id is defined
  block:
    - name: Create group with id
      ansible.builtin.group:
        name: '{{ user_service_name }}'
        gid: '{{ user_service_id }}'
        system: true
    - name: Create user with id
      ansible.builtin.user:
        name: '{{ user_service_name }}'
        uid: '{{ user_service_id }}'
        group: '{{ user_service_name }}'
        shell: /usr/sbin/nologin
        home: '{{ user_service_home | default("/nonexistent") }}'
        create_home: '{{ user_service_home is defined }}'
        system: true

- name: Create user without id
  ansible.builtin.user:
    name: '{{ user_service_name }}'
    shell: /usr/sbin/nologin
    home: '{{ user_service_home | default("/nonexistent") }}'
    create_home: '{{ user_service_home is defined }}'
    system: true
  when: user_service_id is not defined
