---

- name: 'Archive "{{ archive_dest }}" is downloaded'
  ansible.builtin.get_url:
    url: '{{ archive_url }}'
    dest: '{{ archive_dest }}'
    force: false
    owner: root
    group: root
    mode: u=rw,go=r

- name: 'Directory "{{ archive_content }}" exists'
  ansible.builtin.file:
    path: '{{ archive_content }}'
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: 'Archive "{{ archive_dest }}" is extracted into "{{ archive_content }}"'
  when: not ansible_check_mode
  ansible.builtin.unarchive:
    remote_src: true
    src: '{{ archive_url }}'
    dest: '{{ archive_content }}'
    creates: '{{ archive_creates | default(omit) }}'
    owner: root
    group: root
    mode: u+rw,go-w+r
    extra_opts:
      - --transform
      - 's/^{{ archive_transform | default("") }}//'
  notify: '{{ archive_notify | default(omit) }}'
