# Install package

- name: Package
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest

- name: GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    force: yes
    owner: root
    group: root
    mode: ug=rw,o=r

- name: Add apt source
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian bookworm stable
    filename: docker
    update_cache: true

- name: Package
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
