# Apt source

- name: Package gpg
  apt:
    name: gpg
    state: latest

- name: GPG key
  get_url:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    dest: /etc/apt/trusted.gpg.d/plex.asc
    force: yes
    owner: root
    group: root
    mode: ug=rw,o=r

- name: Add apt source
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/plex.asc] https://downloads.plex.tv/repo/deb public main
    filename: plex
    update_cache: true

# Create var

- name: Create var directory
  file:
    path: '{{ plex_var }}'
    state: directory
    owner: '{{ plex_user }}'
    group: '{{ plex_user }}'
    mode: ug=rwx,o=rx

- name: Fix permissions
  shell: >
    find {{ plex_var }} \
      ! -user root \
      ! -user {{ plex_user }} \
      -print \
      -exec chown {{ plex_user }}. {} \; \
      | wc -l
  register: fix_permissions
  changed_when: fix_permissions.stdout != '0'

# Create service override

- name: Create service directory
  file:
    path: /etc/systemd/system/plexmediaserver.service.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Create service
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/plexmediaserver.service.d/override.conf
    owner: root
    group: root
    mode: u=rw,go=r
  register: create_service

# Install package

- name: Package
  apt:
    name: plexmediaserver
    state: latest
  register: package

- name: Remove default plex user
  user:
    name: plex
    state: absent
    remove: yes
  when: plex_user != 'plex'

# Start service

- name: Enable
  systemd: 
    name: plexmediaserver
    enabled: true

- name: Restart
  systemd:
    name: plexmediaserver
    state: restarted
    daemon_reload: true
  when: >
    create_service is changed or
    package is changed

- name: Start 
  systemd: 
    name: plexmediaserver
    state: started
