---

virtual_password_user_root: password
virtual_user_regular_name: david
virtual_password_user_regular: password
virtual_user_ansible_name: ansible
virtual_password_user_ansible: password

virtual_network_interface: enp0s1
virtual_network_hostname: virtual
virtual_network_local_domain: '{{ virtual_network_hostname }}.local'

virtual_disk_system: /dev/vda
