# Install package

- name: Package
  ansible.builtin.apt:
    name:
      - iptables
      - wireguard
    state: present
  register: package

# Configure

- name: Create config
  ansible.builtin.template:
    src: server.conf.j2
    dest: '/etc/wireguard/{{ wireguard_interface_name }}.conf'
    owner: root
    group: root
    mode: u=rw,go=
  no_log: true
  register: create_config

- name: Enable ipv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    reload: true
    state: present

- name: Enable ipv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: true
    reload: true

# Service

- name: Enable
  ansible.builtin.systemd:
    name: 'wg-quick@{{ wireguard_interface_name }}'
    enabled: true

- name: Restart
  ansible.builtin.systemd:
    name: 'wg-quick@{{ wireguard_interface_name }}'
    daemon_reload: true
    state: restarted
  when: >
      package is changed or
      create_config is changed

- name: Start
  ansible.builtin.systemd:
    name: 'wg-quick@{{ wireguard_interface_name }}'
    state: started
