---

name: cd

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.changes.outputs.ansible }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ansible:
              - 'ansible/**'
              - ansible.cfg
  server-playbook:
    name: server-playbook
    runs-on: ubuntu-latest
    concurrency: server
    needs: changes
    if: needs.changes.outputs.ansible == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: server-playbook
        uses: ./.github/actions/ansible
        with:
          command: ansible-playbook -i ansible/inventory/server.davidlsq.fr -D ansible/server.yml
          server-archive: ${{ secrets.SERVER_ARCHIVE }}
