---

name: cd

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.changes.outputs.infra }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            infra:
              - 'roles/**'
              - 'infra/**'
              - ansible.cfg
  playbook-apply-infra-raspi:
    name: playbook-apply-infra-raspi
    runs-on: ubuntu-latest
    concurrency: infra-raspi
    needs: changes
    if: needs.changes.outputs.infra == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: playbook-apply-infra-raspi
        run: >
          ./scripts/ssh-env.sh github@home.davidlsq.fr -p 22
          sudo /usr/lib/installer/run.sh apply main
        env:
          SSH_USER_KEY: ${{ secrets.RASPI_GITHUB_SSH_KEY }}
          SSH_HOST_KEY: ${{ secrets.RASPI_HOST_SSH_KEY }}
  playbook-apply-infra-server:
    name: playbook-apply-infra-server
    runs-on: ubuntu-latest
    concurrency: infra-server
    needs: changes
    if: needs.changes.outputs.infra == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: playbook-apply-infra-server
        run: >
          ./scripts/ssh-env.sh github@home.davidlsq.fr -p 23
          sudo /usr/lib/installer/run.sh apply main
        env:
          SSH_USER_KEY: ${{ secrets.SERVER_GITHUB_SSH_KEY }}
          SSH_HOST_KEY: ${{ secrets.SERVER_HOST_SSH_KEY }}
