---

name: cd

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.changes.outputs.server }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            server:
              - 'roles/**'
              - 'infra/**'
              - ansible.cfg
  playbook:
    name: playbook
    runs-on: ubuntu-latest
    concurrency: server
    needs: changes
    if: needs.changes.outputs.server == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: playbook
        run: |
          make github-pull
          ssh -p 22 -i infra/config/raspi_ssh_keys_github \
              -o GlobalKnownHostsFile=infra/config/ssh_known_host \
              github@home.davidlsq.fr \
              sudo /usr/lib/installer/run.sh main
          ssh -p 23 -i infra/config/server_ssh_keys_github \
              -o GlobalKnownHostsFile=infra/config/ssh_known_host \
              github@home.davidlsq.fr \
              sudo /usr/lib/installer/run.sh main
        env:
          GIHUB_SSH: ${{ secrets.GIHUB_SSH }}
