---

name: cd

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.changes.outputs.server }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            server:
              - 'roles/**'
              - 'server/**'
              - ansible.cfg
  server-playbook:
    name: server-playbook
    runs-on: ubuntu-latest
    concurrency: server
    needs: changes
    if: needs.changes.outputs.server == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: server-playbook-check
        uses: ./.github/actions/nix-shell
        with:
          command: make github-playbook
        env:
          SERVER_ARCHIVE: ${{ secrets.SERVER_ARCHIVE }}
