---

name: cd

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.changes.outputs.server }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            server:
              - 'roles/**'
              - 'infra/**'
              - ansible.cfg
  playbook:
    name: playbook
    runs-on: ubuntu-latest
    concurrency: server
    needs: changes
    if: needs.changes.outputs.server == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: playbook-raspi
        run: >
          ./scripts/ssh-env.sh github@home.davidlsq.fr -p 22
          sudo /usr/lib/installer/run.sh apply main
        env:
          SSH_USER_KEY: ${{ secrets.RASPI_GITHUB_SSH_KEY }}
          SSH_HOST_KEY: ${{ secrets.RASPI_HOST_SSH_KEY }}
      - name: playbook-server
        run: >
          ./scripts/ssh-env.sh github@home.davidlsq.fr -p 23
          sudo /usr/lib/installer/run.sh apply main
        env:
          SSH_USER_KEY: ${{ secrets.SERVER_GITHUB_SSH_KEY }}
          SSH_HOST_KEY: ${{ secrets.SERVER_HOST_SSH_KEY }}
