---

name: ci

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      dependabot: ${{ steps.changes.outputs.dependabot }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            make:
              - config
              - python
              - makefile
            dependabot:
              - .github/dependabot.yml
            ansible:
              - ansible
              - ansible.cfg
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pre-commit
        uses: ./.github/actions/nix-shell
        with:
          command: pre-commit run -a
  make:
    name: make
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.make == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: make
        uses: ./.github/actions/nix-shell
        with:
          command: make build/virtual.iso
      - name: check
        run: ls -lh build; [ -f build/virtual.iso ]
  dependabot:
    name: dependabot
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.dependabot == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: dependabot
        uses: marocchino/validate-dependabot@v2
  server-playbook-check:
    name: server-playbook-check
    runs-on: ubuntu-latest
    concurrency: server
    needs: changes
    if: needs.changes.outputs.ansible == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: server-playbook-check
        uses: ./.github/actions/ansible
        with:
          command: ansible-playbook -i ansible/inventory/server.davidlsq.fr -D -C ansible/server.yml
          server-archive: ${{ secrets.SERVER_ARCHIVE }}
