---

name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      make: ${{ steps.changes.outputs.make }}
      dependabot: ${{ steps.changes.outputs.dependabot }}
      server: ${{ steps.changes.outputs.server }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            make:
              - 'scripts/debian/**'
              - scripts/debian.sh
              - 'roles/config_*/**'
              - virtual/config.yml
              - makefile
            dependabot:
              - .github/dependabot.yml
            server:
              - 'roles/**'
              - 'infra/**'
              - ansible.cfg
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: pre-commit
        uses: ./.github/actions/nix-shell
        with:
          command: pre-commit run -a
  make:
    name: make
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.make == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: make
        uses: ./.github/actions/nix-shell
        with:
          command: make virtual/virtual.iso
      - name: check
        run: ls -lh virtual; [ -f virtual/virtual.iso ]
  dependabot:
    name: dependabot
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.dependabot == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: dependabot
        uses: marocchino/validate-dependabot@v2
  playbook-check:
    name: playbook-check
    runs-on: ubuntu-latest
    concurrency: server
    needs: changes
    if: needs.changes.outputs.server == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: playbook-check
        run: |
          make github-pull
          ssh -p 22 -i infra/config/raspi_ssh_keys_github \
              -o GlobalKnownHostsFile=infra/config/ssh_known_host \
              github@home.davidlsq.fr \
              sudo /usr/lib/installer/run.sh ${{ github.head_ref }} -C
          ssh -p 23 -i infra/config/server_ssh_keys_github \
              -o GlobalKnownHostsFile=infra/config/ssh_known_host \
              github@home.davidlsq.fr \
              sudo /usr/lib/installer/run.sh ${{ github.head_ref }} -C
        env:
          GIHUB_SSH: ${{ secrets.GIHUB_SSH }}
