---

name: ci

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      make: ${{ steps.changes.outputs.make }}
      dependabot: ${{ steps.changes.outputs.dependabot }}
      server: ${{ steps.changes.outputs.server }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            make:
              - build.sh
              - 'roles/config/**'
              - virtual/config.yml
              - makefile
            dependabot:
              - .github/dependabot.yml
            server:
              - 'roles/**'
              - 'server/**'
              - ansible.cfg
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: pre-commit
        uses: ./.github/actions/nix-shell
        with:
          command: pre-commit run -a
  make:
    name: make
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.make == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: make
        uses: ./.github/actions/nix-shell
        with:
          command: make virtual/image.iso
      - name: check
        run: ls -lh virtual; [ -f virtual/image.iso ]
  dependabot:
    name: dependabot
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.dependabot == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: dependabot
        uses: marocchino/validate-dependabot@v2
  server-playbook-check:
    name: server-playbook-check
    runs-on: ubuntu-latest
    concurrency: server
    needs: changes
    if: needs.changes.outputs.server == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: server-playbook-check
        uses: ./.github/actions/nix-shell
        with:
          command: make github-playbook-check
        env:
          SERVER_ARCHIVE: ${{ secrets.SERVER_ARCHIVE }}
