---

name: ci

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pre-commit
        uses: ./.github/actions/nix-shell
        with:
          command: pre-commit run -a
  make:
    name: make
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: make
        uses: ./.github/actions/nix-shell
        with:
          command: make build/virtual.iso
      - name: check
        run: ls -lh build; [ -f build/virtual.iso ]
  server-playbook-check:
    name: server-playbook-check
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: server-archive
        env:
          SERVER_ARCHIVE: ${{ secrets.SERVER_ARCHIVE }}
        run: echo "$SERVER_ARCHIVE" | base64 -d | tar zxf -
      - name: server-playbook-check
        uses: ./.github/actions/nix-shell
        with:
          command: make build/server/ssh && ansible-playbook -i ansible/inventory/server.davidlsq.fr -D -C ansible/server.yml
