---

name: updatebot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  updatebot-joal:
    uses: ./.github/workflows/updatebot-dependency.yml
    secrets: inherit
    with:
      dependency: joal
