---

name: updatebot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  updatebot-tarball-nix:
    uses: ./.github/workflows/updatebot-dependency.yml
    secrets: inherit
    with:
      dependency: tarball_nix
  updatebot-ohmyzsh:
    uses: ./.github/workflows/updatebot-dependency.yml
    secrets: inherit
    with:
      dependency: ohmyzsh
  updatebot-plex:
    uses: ./.github/workflows/updatebot-dependency.yml
    secrets: inherit
    with:
      dependency: plex
  updatebot-joal:
    uses: ./.github/workflows/updatebot-dependency.yml
    secrets: inherit
    with:
      dependency: joal
  updatebot-jackett:
    uses: ./.github/workflows/updatebot-dependency.yml
    secrets: inherit
    with:
      dependency: jackett
