---

name: updatebot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  updatebot:
    runs-on: ubuntu-latest
    name: updatebot
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: updatebot
        uses: ./.github/actions/updatebot
      - name: create-pull-request-tarball-nix
        uses: ./.github/actions/create-pull-request
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: tarball-nix
          path: shell.nix
      - name: create-pull-request-ohmyzsh
        uses: ./.github/actions/create-pull-request
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: ohmyzsh
          path: ansible/roles/ohmyzsh/defaults/main.yml
      - name: create-pull-request-plex
        uses: ./.github/actions/create-pull-request
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: plex
          path: ansible/roles/plex/defaults/main.yml
      - name: create-pull-request-qbittorrent
        uses: ./.github/actions/create-pull-request
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: qbittorrent
          path: ansible/roles/qbittorrent/defaults/main.yml
      - name: create-pull-request-joal
        uses: ./.github/actions/create-pull-request
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: joal
          path: ansible/roles/joal/defaults/main.yml
      - name: create-pull-request-jackett
        uses: ./.github/actions/create-pull-request
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: jackett
          path: ansible/roles/jackett/defaults/main.yml
      - name: create-pull-request-radarr
        uses: ./.github/actions/create-pull-request
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: radarr
          path: ansible/roles/servarr/vars/radarr.yml
