- name: Get change
  ansible.builtin.uri:
    url: '{{ checkmk_api_url }}/domain-types/activation_run/collections/pending_changes'
    headers:
      Authorization: 'Bearer automation {{ checkmk_automation_password }}'
      Accept: application/json
  register: get_change
  no_log: true

- name: Apply change
  when:
    - not ansible_check_mode
    - get_change.json.value
  ansible.builtin.uri:
    url: '{{ checkmk_api_url }}/domain-types/activation_run/actions/activate-changes/invoke'
    method: POST
    headers:
      Authorization: 'Bearer automation {{ checkmk_automation_password }}'
      Accept: application/json
      Content-Type: application/json
      If-Match: '{{ get_change.etag }}'
    body:
      force_foreign_changes: true
      redirect: false
      sites: ['{{ checkmk_site }}']
    body_format: json
  changed_when: true
  no_log: true
