- name: Get host
  ansible.builtin.uri:
    url: '{{ checkmk_api_url }}/objects/host_config/{{ item.name }}'
    headers:
      Authorization: 'Bearer automation {{ checkmk_automation_password }}'
      Accept: application/json
    status_code: [200, 404]
  register: get_host
  no_log: true

- name: Create host
  when:
    - not ansible_check_mode
    - get_host.status == 404
  ansible.builtin.uri:
    url: '{{ checkmk_api_url }}/domain-types/host_config/collections/all'
    method: POST
    headers:
      Authorization: 'Bearer automation {{ checkmk_automation_password }}'
      Accept: application/json
      Content-Type: application/json
    body:
      attributes:
        ipaddress: '{{ item.ip_address }}'
      folder: /
      host_name: '{{ item.name }}'
    body_format: json
  changed_when: true
  no_log: true
