- name: Get user
  ansible.builtin.uri:
    url: '{{ checkmk_api_url }}/objects/user_config/{{ item }}'
    headers:
      Authorization: 'Bearer automation {{ checkmk_automation_password }}'
      Accept: application/json
    status_code: [200, 404]
  register: get_user
  no_log: true

- name: Create user
  when:
    - not ansible_check_mode
    - get_user.status == 404
  ansible.builtin.uri:
    url: '{{ checkmk_api_url }}/domain-types/user_config/collections/all'
    method: POST
    headers:
      Authorization: 'Bearer automation {{ checkmk_automation_password }}'
      Accept: application/json
      Content-Type: application/json
    body:
      username: '{{ item }}'
      fullname: '{{ item }}'
      roles:
        - user
    body_format: json
  changed_when: true
  no_log: true
