# Install package

- name: Package
  ansible.builtin.apt:
    name: default-jre
    state: present

# Create lib

- name: Create lib directory
  ansible.builtin.file:
    path: '{{ joal_lib }}'
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Create lib
  ansible.builtin.unarchive:
    src: '{{ joal_archive }}'
    remote_src: true
    dest: '{{ joal_lib }}'
    owner: root
    group: root
    mode: u+rw,go-w+r
    creates: '{{ joal_lib }}/jack-of-all-trades-{{ joal_version }}.jar'
  ignore_errors: "{{ ansible_check_mode }}"
  register: create_lib

# Create var

- name: Create var directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ joal_user }}'
    group: '{{ joal_user }}'
    mode: ug=rwx,o=rx
  with_items:
    - '{{ joal_var }}'
    - '{{ joal_var }}/clients'
    - '{{ joal_var }}/torrents'
    - '{{ joal_var }}/torrents/archived'

- name: Create client config
  ansible.builtin.copy:
    src: '{{ joal_lib }}/clients/{{ joal_client }}.client'
    remote_src: true
    dest: '{{ joal_var }}/clients/{{ joal_client }}.client'
    owner: '{{ joal_user }}'
    group: '{{ joal_user }}'
    mode: ug=rw,o=r
  register: create_client_config
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create config
  ansible.builtin.template:
    src: config.json.j2
    dest: '{{ joal_var }}/config.json'
    owner: '{{ joal_user }}'
    group: '{{ joal_user }}'
    mode: ug=rw,o=r
  register: create_config

- name: Fix permissions
  ansible.builtin.shell: >
    set -e -o pipefail
    find {{ joal_var }} \
      ! -user root \
      ! -user {{ joal_user }} \
      -print \
      -exec chown {{ joal_user }}. {} \; \
      | wc -l
  register: fix_permissions
  changed_when: fix_permissions.stdout != '0'
  tags: fix_permissions

# Create service

- name: Create service
  ansible.builtin.template:
    src: service.j2
    dest: '/etc/systemd/system/{{ joal_name }}.service'
    owner: root
    group: root
    mode: u=rw,go=r
  register: create_service

- name: Enable
  ansible.builtin.systemd:
    name: '{{ joal_name }}'
    enabled: true

- name: Restart
  ansible.builtin.systemd:
    name: '{{ joal_name }}'
    state: restarted
    daemon_reload: true
  when: >
    create_lib is changed or
    create_client_config is changed or
    create_config is changed or
    create_service is changed

- name: Start
  ansible.builtin.systemd:
    name: '{{ joal_name }}'
    state: started
